class trans1 extends uvm_sequence_item;
   
	rand logic wr;
	rand logic [7:0] mem_addr;
	rand logic [7:0] mem_data;
	rand logic [7:0] data_write;
	logic [7:0] data_read;
	logic [7:0] target_addr;
	logic [7:0] tb_addr_data;
	logic [4:0] tb_count;
    
	int addr[$]; //store all the memory address generated by sequence item
	int data[$]; //store all the memory data generated by sequence item
	
	`uvm_object_utils(trans1)
    
    function new(string name = "trans1");
        super.new(name);
    endfunction
	
	virtual function string input2string();
		return($sformatf("input signals:"));
	endfunction


	virtual function string output2string();
		return($sformatf("output signals"));
	endfunction

	virtual function string convert2string();
		return({input2string(), " ", output2string()});
	endfunction

endclass
